on:
  schedule:
    - cron: '*/5 * * * *'

name: Fetch and store

jobs:
  fetch:
    name: Fetch and store
    runs-on: ubuntu-latest
    container: buildkite/puppeteer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Scrape
      run: |
        yarn
        node scrape.js
