on:
  schedule:
    - cron: '0,2,5,10 10 * * *' # runs at 8:00pm, 8:02pm, 8:05pm, 8:15pm (AEST)
    - cron: '13 * * * *' # runs hourly thereafter at 13 past the hour
    # - cron: '0,2,5,10 9 * * *' # runs at 8:00pm, 8:02pm, 8:05pm, 8:15pm (AEDT)
  push:
    branches:
      - master

name: Fetch and store

jobs:
  fetch:
    name: Fetch and store
    runs-on: ubuntu-latest
    container: buildkite/puppeteer
    steps:
    - name: Install other dependencies
      run: |
          apt update
          apt install -y git
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Scrape
      timeout-minutes: 3
      run: |
        yarn
        node scrape.js
        node generate-csv.js
    - name: Push data
      run: |
          git config user.name jxeeno
          git config user.email ken+github@jxeeno.com
          git add . || exit 0
          git commit -m "auto(): update data" || exit 0
          git push || exit 0
